name: kingdomino_score_count
description: Calculate your Kingdomino score easly

version: 2.1.0+15

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  package_info: ^2.0.0
  flutter_svg: ^0.21.0+1
  camera: ^0.8.1
  path_provider:
  path:


dev_dependencies:
  test: ^1.16.5
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  fonts:
    - family: Augusta
      fonts:
        - asset: fonts/Augusta.ttf
    - family: HammersmithOne
      fonts:
        - asset: fonts/HammersmithOne-Regular.ttf
