name: kingdomino_score_count
description: Calculate your Kingdomino score easly

version: 2.0.8+14

environment:
  sdk: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^2.1.0
  material_design_icons_flutter: ^4.0.5655
  package_info: ^2.0.0
  flutter_svg: ^0.21.0+1

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  fonts:
    - family: Augusta
      fonts:
        - asset: fonts/Augusta.ttf
    - family: HammersmithOne
      fonts:
        - asset: fonts/HammersmithOne-Regular.ttf
