name: kingdomino_score_count
description: Calculate your Kingdomino score easly

version: 2.2.0+16

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  package_info: ^2.0.0
  flutter_svg: ^0.22.0
  camera: ^0.8.1
  path_provider: ^2.0.1
  path: ^1.8.0
  image: ^3.0.2
  ffi: ^1.0.0
  image_cropper: ^1.4.0
  native_opencv:
    path: native_opencv


dev_dependencies:
  test: ^1.16.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/quests/
    - assets/lacour/
    - assets/tiles/
    - assets/histograms/
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  fonts:
    - family: Augusta
      fonts:
        - asset: fonts/Augusta.ttf
    - family: HammersmithOne
      fonts:
        - asset: fonts/HammersmithOne-Regular.ttf
